spring:
  cloud:
    gateway:
      routes:
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
  application:
    name: api-gateway
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


