spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 9001
  servlet:
    context-path: /users
jwt:
  secretKey: secretfjdgvgviughiuhiuehfmshbvksfgjkshgf
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

